@startuml
skinparam classAttributeIconSize 0

class Client {
}

abstract class Target {
    {abstract} +targetMethod1()
    {abstract} +targetMethod2()
}

class Adapter {
    -adaptee
    +targetMethod1()
    +targetMethod2()  
}

class Adaptee {
    +MethodA()
    +MethodB()
    +MethodC()
}

Client --> Target : Uses >
Target <|-- Adapter : extends >
Adaptee <--o Adapter : has >

@enduml
